#!/bin/bash

#purpose: clean up files when not needed
if [ "$#" -ne 1 ]; then
    echo "usage: process.sh (filename - conf) "
    exit 1
fi

#get the first line of the file
line=$(head -n 1 $1)
echo "Data Type:  $line"

#clean up any files that would be generated by these files
rm "$line""_template.java"
rm "$line""_template.class"
rm "java_template.class"
rm "java_template_generator.class"
rm "$line.java"
rm "$line.class"
